[package]
name = "leetcde_1071_gcd_strings"
version = "0.1.0"
edition = "2024"

[dependencies]


[target."cfg(hax)".dependencies]
hax-lib = { git = "https://github.com/hacspec/hax", version = "0.3.5" }
