name = "leetcde_283_with_hax"
version = "0.1.0"
defaultTargets = ["leetcde_283_with_hax"]

[[lean_lib]]
name = "leetcde_283_with_hax"

[[require]]
name = "Hax"
git = "https://github.com/cryspen/hax"
subDir = "hax-lib/proof-libs/lean"
rev = "main"